<form action="/users">
  <input type="search" name="term" value="<?= htmlspecialchars($term) ?>">
  <input type="submit" value="Search">
</form>

<?php foreach ($users as $user): ?>
    <table>
        <div>
        <tr> <?= htmlspecialchars($user['name'])?> </tr> 
        <tr> <?= htmlspecialchars($user['email'])?> </tr>
</div>
</table>
  <?php endforeach ?>
 
  

  <?php if (count($flash) > 0) : ?>
                    <?php foreach ($flash as $messages) : ?>
                        <?php foreach ($messages as $message) : ?>
                                <a><?= $message ?></a>
                            </div>
                        <?php endforeach ?>
                    <?php endforeach ?>
                <?php endif ?>


